[project]
name = "my-big-baby"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "xlrd>=2.0.2",
]
